matrix:
  include:
    - os: linux
      dist: focal
      arch: amd64
      env: IRAFARCH=linux64 OS_VERS=focal RATFOR=ratfor
      addons:
        apt:
          update: true
          packages:
            - libcurl4-openssl-dev
            - libexpat1-dev
            - libreadline-dev
            - ratfor
    - os: linux
      dist: bionic
      env: IRAFARCH=linux OS_VERS=bionic CARCH="-m32"
      addons:
        apt:
          packages:
            - gcc-multilib
            - libcurl4-openssl-dev:i386
            - libexpat1-dev:i386
            - libreadline-dev:i386
    - os: osx
      osx_image: xcode12.2
      env: IRAFARCH=macintel OS_VERS=catalina
    - os: osx
      osx_image: xcode9.4
      env: IRAFARCH=macosx OS_VERS=highsierra CARCH="-m32"

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install ccache; PATH=/usr/local/opt/ccache/libexec:$PATH ; fi

language: c

cache:
  ccache: true
  directories:
    - $HOME/.ccache

git:
  depth: 3

before_script:
  - build_tmp=$(mktemp -d -t irafbuild.XXXXXXXXX)
  - mkdir -p ${build_tmp}/bin
  - PATH=${build_tmp}/bin:$PATH
  - ./install --term xterm --bindir $build_tmp/bin --cache $build_tmp/cache --imdir $build_tmp/imdir < /dev/null || true
  - make ${IRAFARCH}
  - make sysgen

script:
  - ./test/run_tests
