
name: IRAF CI test

on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      CARCH: ${{ matrix.carch }}

    strategy:
      matrix:
        include:
          - name: Ubuntu latest x86_64
            os: ubuntu-latest

          - name: Ubuntu 20.04 Focal i386
            os: ubuntu-20.04
            irafarch: linux
            carch: '-m32'

          - name: macOS x86_64
            os: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          if [ ${CARCH} == '-m32' ] ; then
            sudo dpkg --add-architecture i386
            sudo apt-get update -y
            sudo apt-get install -y gcc-multilib libcurl4-openssl-dev:i386 libexpat1-dev:i386 libreadline-dev:i386 zlib1g-dev:i386
          else
            sudo apt-get update -y
            sudo apt-get install -y build-essential libcurl4-openssl-dev libexpat1-dev libreadline-dev zlib1g-dev
          fi

      - name: Setup non-standard IRAF build (32 bit)
        if: matrix.irafarch == 'linux'
        run: |
          IRAFARCH=linux make

      - name: Build IRAF
        if: matrix.irafarch != 'linux'
        run: |
          make

      - name: Run tests
        run: |
         make test
